#!/bin/bash
## Author: arturos@cern.ch
## September 30th 2013
##
## INTRUCTIONS:
## Taking the file produced with: ls *.root >root_files
## after you move the root files outside the 
## datasets that you downloaded, creating the file called 
## "root_files" that is the input ($1) of this script.
##
#################################################################
FILE=$1                                                        ##
k=1                                                            ##
while read files;do                                            ##
        sample=${files//"mc12_8TeV."/}                         ##
	sample=${sample//.root/}                               ##
	sampleE=$sample"_E2.root"                              ##
	sampleM=$sample"_MU2.root"                             ##
        echo "cp $files $sampleE"                              ##
        echo "cp $files $sampleM"                              ##
        ((k++))                                                ##
done  < $FILE                                                  ##
                                                               ##
echo "  "                                                      ##
echo "        ## Total number of Samples to be copied: $k ##"  ##
echo "               ################################"         ##
echo "  "                                                      ##
#################################################################
