#!/bin/bash
## author: arturos@cern.ch
## September 30th 2013
## Taking the file produced with: ls *.root >root_files
#############################################################################
FILE=$1

k=1
while read files;do
        sample=${files//mc12_8TeV./}
	sample=${files//.root/}
        echo "cp $files  $sample_E2.root"   
        echo "cp $files $sample_MU2.root"   
        ((k++))
done  < $FILE

echo "  "
echo "        ## Total number of Samples to be produce: $k ##"
echo "               ################################"
echo "  "
#############################################################################
