{
  c_4mu = new TCanvas("c_4mu", "4mu");
  eff_vs_mH_4mu_mc12->SetLineColor(kRed);
  eff_vs_mH_4mu_mc11c->Draw();
  c_4mu->Update();
  eff_vs_mH_4mu_mc11c->GetPaintedGraph()->GetXaxis()->SetTitle("m_{H} [GeV]");
  eff_vs_mH_4mu_mc11c->GetPaintedGraph()->GetYaxis()->SetTitle("# 4#mu sel. evts / # evts passing truth filter");
  eff_vs_mH_4mu_mc12->Draw("same");
  eff_vs_mH_4mu_mc12->SetTitle("mc12");
  eff_vs_mH_4mu_mc11c->SetTitle("mc11c");
  eff_vs_mH_4mu_mc12->SetFillColor(0);
  eff_vs_mH_4mu_mc11c->SetFillColor(0);
  TLegend *leg_4mu = c_4mu->BuildLegend();
  leg_4mu->SetFillColor(0);
  leg_4mu->SetBorderSize(0);

  c_2mu2e = new TCanvas("c_2mu2e", "2mu2e");
  eff_vs_mH_2mu2e_mc12->SetLineColor(kRed);
  eff_vs_mH_2mu2e_mc11c->Draw();
  c_2mu2e->Update();
  eff_vs_mH_2mu2e_mc11c->GetPaintedGraph()->GetXaxis()->SetTitle("m_{H} [GeV]");
  eff_vs_mH_2mu2e_mc11c->GetPaintedGraph()->GetYaxis()->SetTitle("# 2e2#mu sel. evts / # evts passing truth filter");
  eff_vs_mH_2mu2e_mc12->Draw("same");
  eff_vs_mH_2mu2e_mc12->SetTitle("mc12");
  eff_vs_mH_2mu2e_mc11c->SetTitle("mc11c");
  eff_vs_mH_2mu2e_mc12->SetFillColor(0);
  eff_vs_mH_2mu2e_mc11c->SetFillColor(0);
  TLegend *leg_2mu2e = c_2mu2e->BuildLegend();
  leg_2mu2e->SetFillColor(0);
  leg_2mu2e->SetBorderSize(0);

  c_4e = new TCanvas("c_4e", "4e");
  eff_vs_mH_4e_mc12->SetLineColor(kRed);
  eff_vs_mH_4e_mc11c->Draw();
  c_4e->Update();
  eff_vs_mH_4e_mc11c->GetPaintedGraph()->GetXaxis()->SetTitle("m_{H} [GeV]");
  eff_vs_mH_4e_mc11c->GetPaintedGraph()->GetYaxis()->SetTitle("# 4e sel. evts / # evts passing truth filter");
  eff_vs_mH_4e_mc12->Draw("same");
  eff_vs_mH_4e_mc12->SetTitle("mc12");
  eff_vs_mH_4e_mc11c->SetTitle("mc11c");
  eff_vs_mH_4e_mc12->SetFillColor(0);
  eff_vs_mH_4e_mc11c->SetFillColor(0);
  TLegend *leg_4e = c_4e->BuildLegend();
  leg_4e->SetFillColor(0);
  leg_4e->SetBorderSize(0);

  c_4mu->Update();
  c_2mu2e->Update();
  c_4e->Update();
  getchar();

  c_mc11c = new TCanvas("c_mc11c", "mc11c");
  eff_vs_mH_4mu_mc11c->SetLineColor(kBlack);
  eff_vs_mH_2mu2e_mc11c->SetLineColor(kBlue+1);
  eff_vs_mH_4e_mc11c->SetLineColor(kRed);
  eff_vs_mH_4mu_mc11c->SetFillColor(0);
  eff_vs_mH_2mu2e_mc11c->SetFillColor(0);
  eff_vs_mH_4e_mc11c->SetFillColor(0);
  eff_vs_mH_4mu_mc11c->SetTitle("4#mu");
  eff_vs_mH_2mu2e_mc11c->SetTitle("2#mu2e");
  eff_vs_mH_4e_mc11c->SetTitle("4e");
  eff_vs_mH_4mu_mc11c->Draw();
  c_mc11c->Update();
  eff_vs_mH_4mu_mc11c->GetPaintedGraph()->GetXaxis()->SetTitle("m_{H} [GeV]");
  eff_vs_mH_4mu_mc11c->GetPaintedGraph()->GetYaxis()->SetTitle("# mc11c sel. evts / # evts passing truth filter");
  eff_vs_mH_2mu2e_mc11c->Draw("same");
  eff_vs_mH_4e_mc11c->Draw("same");
  TLegend *leg_mc11c = c_mc11c->BuildLegend();
  leg_mc11c->SetFillColor(0);
  leg_mc11c->SetBorderSize(0);

  c_mc12 = new TCanvas("c_mc12", "mc12");
  eff_vs_mH_4mu_mc12->SetLineColor(kBlack);
  eff_vs_mH_2mu2e_mc12->SetLineColor(kBlue+1);
  eff_vs_mH_4e_mc12->SetLineColor(kRed);
  eff_vs_mH_4mu_mc12->SetFillColor(0);
  eff_vs_mH_2mu2e_mc12->SetFillColor(0);
  eff_vs_mH_4e_mc12->SetFillColor(0);
  eff_vs_mH_4mu_mc12->SetTitle("4#mu");
  eff_vs_mH_2mu2e_mc12->SetTitle("2#mu2e");
  eff_vs_mH_4e_mc12->SetTitle("4e");
  eff_vs_mH_4mu_mc12->Draw();
  c_mc12->Update();
  eff_vs_mH_4mu_mc12->GetPaintedGraph()->GetXaxis()->SetTitle("m_{H} [GeV]");
  eff_vs_mH_4mu_mc12->GetPaintedGraph()->GetYaxis()->SetTitle("# mc12 sel. evts / # evts passing truth filter");
  eff_vs_mH_2mu2e_mc12->Draw("same");
  eff_vs_mH_4e_mc12->Draw("same");
  TLegend *leg_mc12 = c_mc12->BuildLegend();
  leg_mc12->SetFillColor(0);
  leg_mc12->SetBorderSize(0);
}
