{
  std::cout << "ggH130_4mu_syst_nominal: " << (ggH130_4mu_syst_nominal->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_PS1_up: " << (ggH130_4mu_syst_PS1_up->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_PS1_down: " << (ggH130_4mu_syst_PS1_down->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_PS2_up: " << (ggH130_4mu_syst_PS2_up->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_PS2_down: " << (ggH130_4mu_syst_PS2_down->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_MAT1_up: " << (ggH130_4mu_syst_MAT1_up->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_MAT1_down: " << (ggH130_4mu_syst_MAT1_down->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_MAT2_up: " << (ggH130_4mu_syst_MAT2_up->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_MAT2_down: " << (ggH130_4mu_syst_MAT2_down->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_ES_Z_up: " << (ggH130_4mu_syst_ES_Z_up->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_ES_Z_down: " << (ggH130_4mu_syst_ES_Z_down->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_ES_lowpt_up: " << (ggH130_4mu_syst_ES_lowpt_up->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_ES_lowpt_down: " << (ggH130_4mu_syst_ES_lowpt_down->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_MUONS_up: " << (ggH130_4mu_syst_MUONS_up->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4mu_syst_MUONS_down: " << (ggH130_4mu_syst_MUONS_down->GetRMS() - ggH130_4mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
std::cout << std::endl;
  std::cout << "ggH130_2mu2e_syst_nominal: " << (ggH130_2mu2e_syst_nominal->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_PS1_up: " << (ggH130_2mu2e_syst_PS1_up->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_PS1_down: " << (ggH130_2mu2e_syst_PS1_down->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_PS2_up: " << (ggH130_2mu2e_syst_PS2_up->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_PS2_down: " << (ggH130_2mu2e_syst_PS2_down->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_MAT1_up: " << (ggH130_2mu2e_syst_MAT1_up->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_MAT1_down: " << (ggH130_2mu2e_syst_MAT1_down->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_MAT2_up: " << (ggH130_2mu2e_syst_MAT2_up->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_MAT2_down: " << (ggH130_2mu2e_syst_MAT2_down->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_ES_Z_up: " << (ggH130_2mu2e_syst_ES_Z_up->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_ES_Z_down: " << (ggH130_2mu2e_syst_ES_Z_down->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_ES_lowpt_up: " << (ggH130_2mu2e_syst_ES_lowpt_up->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_ES_lowpt_down: " << (ggH130_2mu2e_syst_ES_lowpt_down->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_MUONS_up: " << (ggH130_2mu2e_syst_MUONS_up->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2mu2e_syst_MUONS_down: " << (ggH130_2mu2e_syst_MUONS_down->GetRMS() - ggH130_2mu2e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
std::cout << std::endl;
  std::cout << "ggH130_2e2mu_syst_nominal: " << (ggH130_2e2mu_syst_nominal->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_PS1_up: " << (ggH130_2e2mu_syst_PS1_up->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_PS1_down: " << (ggH130_2e2mu_syst_PS1_down->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_PS2_up: " << (ggH130_2e2mu_syst_PS2_up->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_PS2_down: " << (ggH130_2e2mu_syst_PS2_down->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_MAT1_up: " << (ggH130_2e2mu_syst_MAT1_up->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_MAT1_down: " << (ggH130_2e2mu_syst_MAT1_down->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_MAT2_up: " << (ggH130_2e2mu_syst_MAT2_up->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_MAT2_down: " << (ggH130_2e2mu_syst_MAT2_down->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_ES_Z_up: " << (ggH130_2e2mu_syst_ES_Z_up->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_ES_Z_down: " << (ggH130_2e2mu_syst_ES_Z_down->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_ES_lowpt_up: " << (ggH130_2e2mu_syst_ES_lowpt_up->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_ES_lowpt_down: " << (ggH130_2e2mu_syst_ES_lowpt_down->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_MUONS_up: " << (ggH130_2e2mu_syst_MUONS_up->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_2e2mu_syst_MUONS_down: " << (ggH130_2e2mu_syst_MUONS_down->GetRMS() - ggH130_2e2mu_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
std::cout << std::endl;
  std::cout << "ggH130_4e_syst_nominal: " << (ggH130_4e_syst_nominal->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_PS1_up: " << (ggH130_4e_syst_PS1_up->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_PS1_down: " << (ggH130_4e_syst_PS1_down->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_PS2_up: " << (ggH130_4e_syst_PS2_up->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_PS2_down: " << (ggH130_4e_syst_PS2_down->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_MAT1_up: " << (ggH130_4e_syst_MAT1_up->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_MAT1_down: " << (ggH130_4e_syst_MAT1_down->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_MAT2_up: " << (ggH130_4e_syst_MAT2_up->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_MAT2_down: " << (ggH130_4e_syst_MAT2_down->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_ES_Z_up: " << (ggH130_4e_syst_ES_Z_up->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_ES_Z_down: " << (ggH130_4e_syst_ES_Z_down->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_ES_lowpt_up: " << (ggH130_4e_syst_ES_lowpt_up->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_ES_lowpt_down: " << (ggH130_4e_syst_ES_lowpt_down->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_MUONS_up: " << (ggH130_4e_syst_MUONS_up->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
  std::cout << "ggH130_4e_syst_MUONS_down: " << (ggH130_4e_syst_MUONS_down->GetRMS() - ggH130_4e_syst_nominal->GetRMS()) << " GeV shift in histogram rms" << std::endl;	
std::cout << std::endl;
}
